name: macOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DWERROR=ON

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
          cd build
          ctest --output-on-failure
